### ISSUE TITLE
   [ReflectionException]   Class hash does not exist 

### ISSUE THREAD

**Issue by ehababoshehab** [adaojunior/passport-social-grant#13]
hey,

I got this error while installing it, I am using laravel 5.4 and passport 2.0 ...
how can i fix this issue ?

  [ReflectionException]
  Class hash does not exist
Script php artisan optimize handling the post-update-cmd event returned with error code 1
Installation failed, reverting ./composer.json to its original content.

**Comment by adaojunior** [comment]
Hi, I doesn't seems to be a problem with this package.
Did you figure out the problem ?
