### ISSUE TITLE
Where should i place file SocialUserResolver ?

### ISSUE THREAD

**Issue by kprovorov** [adaojunior/passport-social-grant#14]
Trying to use your library, but get error:
`Target [Adaojunior\Passport\SocialUserResolverInterface] is not instantiable while building [\Laravel\Passport\Http\Controllers\AccessTokenController].`

![2017-06-06 18 43 01](https://user-images.githubusercontent.com/20870537/26838210-282e5c18-4ae8-11e7-9c4d-8783b397451f.png)

**Comment by salmanhijazi** [comment]
Place the SocialUserResolver in the same folder as the other files in the package. In SocialGrantServiceProvider.php change SocialUserResolverInterface::class to SocialUserResolver::class

**Comment by adaojunior** [comment]
Did you add `$this->app->singleton(SocialUserResolverInterface::class, SocialUserResolver::class);` on your `AppServiceProvider ` ?

**Comment by salmanhijazi** [comment]
Nope, no need for Singleton. I actually furthered this and placed the the SocialUserResolver file in the Http/Controller folder and referenced that in the SocialGrantServiceProvider file. It felt weird to place my custom code within the Vendor folder. Not sure if that's a good idea, but if it is, maybe add that to the next update and leave instructions in the readme would be good for many who have this confusion?

**Comment by alanTorresManci** [comment]
@salmanhijazi Your answer was a life savior for me

**Comment by salmanhijazi** [comment]
@alanTorresManci I actually came up with a non-destructive way, so you won't have to update the code after every composer update. 

Undo the changes you made to the vendor file, as mentioned in my previous comment. In your AppServiceProvider.php file, place this line in the register() function:

`$this->app->singleton('Adaojunior\Passport\SocialUserResolverInterface', 'App\Http\Controllers\SocialUserResolver');`

Change the SocialUserResolver path if you need to.

Cheers

**Comment by peterbayona** [comment]
I already tried the mentioned but I get this error
`Class App\Http\Controllers\SocialUserResolver cannot extend from interface Adaojunior\Passport\SocialUserResolverInterface`

**Comment by agtoncerqueira** [comment]
Good evening guys, I'm trying run this package but I don't know where is the file "Class App\Http\Controllers\SocialUserResolver ".
I need create it manually?
About the client_id param I'm using this one "Laravel Personal Access Client" already registered automatically with passport.
Implicit Grant Authentication it's a little complicate because never working on route and the documentation its uncompleted for...

**Comment by adaojunior** [comment]
> I need create it manually?

Yes, you need to implement the `SocialUserResolverInterface`, something like this:

```
namespace App\Auth;

use Adaojunior\Passport\SocialUserResolverInterface;

class SocialUserResolver implements SocialUserResolverInterface
{
   public function resolve($network, $accessToken, $accessTokenSecret = null)
   {
        /// your implementation goes here
       dd($network, $accessToken, $accessTokenSecret);
   }
}

```

**Comment by agtoncerqueira** [comment]
thanks guy, It is returned params...
I have another question.
$accessTokenSecret returned null why?
My params is:
grant_type= social,
client_secret = ***,
client_id = 1,
network = facebook,
access_token = TOKEN FROM FACEBOOK 
Is it right? Which method in this class I can generate token from passport?
thank you for your support!!!

**Comment by adaojunior** [comment]
Try something like this:

```
Route::get('testing-route', function(){
    $proxy = Request::create(
        '/oauth/token',
        'POST',
        [
            'grant_type' => 'social',
            'client_id' => 'USE_A_VALID_ID',
            'client_secret' => 'USE_A_VALID_CLIENT_SECRET',
            'network' => 'facebook',
            'access_token' => 'JUST_A_FAKE_STRING',
        ]
    );

    return app()->handle($proxy);
})

```

See if you get a non-null value there. It never happened to me to get a `NULL` value.

**Comment by agtoncerqueira** [comment]
I got error {"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check the `grant_type` parameter"}.
About it the route I thought that was this one 'oauth/authorize'  with GET request?

**Comment by adaojunior** [comment]
Did you register the service provider (if you're not on L 5.5) ?

**Comment by agtoncerqueira** [comment]
Yes, I did! I did everything that documentation ask as Passport as this package!
I set up **AuthServiceProvider**.
$this->registerPolicies();
Passport::routes();
Passport::enableImplicitGrant();

And **AppServiceProvider** too.
$this->app->singleton('Adaojunior\Passport\SocialUserResolverInterface', 'App\Http\Controllers\SocialUserResolver');

Nothing working, I'm very upset with this authentication method on passport because nothing working him!
I'm so sorry guy for uncomfortable, but I guess your package it's my solution!!!

**Comment by adaojunior** [comment]
I just created an example of how to exchange a access token to a passport token, see: https://github.com/adaojunior/passport-social-grant-example
This is just one way of implementing it, you may be getting the access token on the front-end or maybe mobile, in this case you don't need `AuthController::redirect`, instead just send your token to AuthController::callback.
