### ISSUE TITLE
Passport 4 support

### ISSUE THREAD

**Issue by maximepvrt** [adaojunior/passport-social-grant#20]
thanks :-)

**Comment by adaojunior** [comment]
@maximepvrt any change you can send a PR with the changes ? I don't have a project depending on passport 4.0 that I can test with.

**Comment by adaojunior** [comment]
My guess it is a matter of changing `"laravel/passport": "^2.0|^3.0"` to `"laravel/passport": "^2.0|^3.0|^4.0"`

**Comment by maximepvrt** [comment]
yes :-) I have tested by forcing installation with 4. * and I haven't problems.

**Comment by sylouuu** [comment]
I need it too :)

**Comment by adaojunior** [comment]
Updated! It now supports passport 4 and Package Auto-Discovery.
