### ISSUE TITLE
Getting "unsupported_grant_type" after the request is sent.

### ISSUE THREAD

**Issue by kennyhorna** [adaojunior/passport-social-grant#23]
Hello, I'm having some trouble when trying to use the package. I've:
1. Added the package
```php
composer require adaojunior/passport-social-grant
```
2. Add the provider in `config\app.php` (had to do it manually, don't know why Laravel didn't registered automatically - v5.5):
```php
        /*
         * Package Service Providers...
         */
        Adaojunior\Passport\SocialGrantServiceProvider::class,
```
3. Added the singleton line `AppServiceProvider.php`:
```php
    public function register()
    {
        $this->app->singleton(
            'Adaojunior\Passport\SocialUserResolverInterface',
            'App\Utils\SocialUserResolver');
    }
```
<details>
  <summary>4. Created the `SocialUserResolver` class: (clic to expand)</summary>

  ```php
namespace App\Utils;

use Adaojunior\Passport\SocialGrantException;
use Adaojunior\Passport\SocialUserResolverInterface;
use Laravel\Socialite\Facades\Socialite;

class SocialUserResolver implements SocialUserResolverInterface
{

    /**
     * Resolves user by given network and access token.
     *
     * @param string $network
     * @param string $accessToken
     * @param null $accessTokenSecret
     * @return \Illuminate\Http\JsonResponse|mixed
     * @throws SocialGrantException
     */
    public function resolve($network, $accessToken, $accessTokenSecret = null)
    {
        switch ($network) {
            case 'facebook':
                return $this->authWithFacebook($accessToken);
                break;
            default:
                throw SocialGrantException::invalidNetwork();
                break;
        }
    }


    /**
     * Resolves user by facebook access token.
     *
     * @param string $accessToken
     * @return \Illuminate\Http\JsonResponse
     */
    protected function authWithFacebook($accessToken)
    {
        $user = Socialite::driver('facebook')->userFromToken($accessToken);

        if ( ! is_null($user) ) {
            return $user;
        }
        else {
            return response()->json([
                "message" => "invalid_credentials",
                "errors" => "The facebook's id of the user does not exist in the system.",
            ], 404);
        }
    }
}
```
</details>
<br>

5. And this is my method in my `AuthController`:
```php
// some other code

    public function facebookLogin(FacebookLoginRequest $request)

        $request->request->add([
            'grant_type' => 'social',
            'client_id' => 'YYYYYYYYYYYY',
            'client_secret' => 'XXXXXXXXXXXXXXXXXXXXX',
            'network' => 'facebook',
            'access_token' => $request->facebook_token,
        ]);

        $proxy = Request::create(
            '/oauth/token',
            'POST'
        );

        return Route::dispatch($proxy);

    }

// some other code
```

But after all that, i'me getting this error response, it seems that Passport doesn't recognize the `grant_type` that the package defines:
```json
{
    "error": "unsupported_grant_type",
    "message": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check the `grant_type` parameter"
}
```

**Comment by ekstro** [comment]
Same problem here.

**Comment by ekstro** [comment]
@ke3nnix If you are on =< 5.4 please manually register service provider.

**Comment by ekstro** [comment]
@ke3nnix don't you forget to register service provider?

**Comment by ekstro** [comment]
@ke3nnix don't forget to register service provider.

**Comment by kennyhorna** [comment]
@ekstro as you can see in the step 2 of my question, I did.. or you are referring to another file?

**Comment by adaojunior** [comment]
Did you something like this ?

```
    $http = new GuzzleHttp\Client;

    $response = $http->post('http://your-app.com/oauth/token', [
        'form_params' => [
            'grant_type' => 'social',
            'client_id' => 'YYYYYYYYYYYY',
            'client_secret' => 'XXXXXXXXXXXXXXXXXXXXX',
            'network' => 'facebook',
            'access_token' => $request->facebook_token,
        ],
    ]);

    return json_decode((string) $response->getBody(), true);
```

**Comment by adaojunior** [comment]
But if you prefer to use the "proxy", you will have to do something like this:

```
    $proxy = Request::create(
        '/oauth/token',
        'POST',
        [
            'grant_type' => 'social',
            'client_id' => 'YYYYYYYYYYYY',
            'client_secret' => 'XXXXXXXXXXXXXXXXXXXXX',
            'network' => 'facebook',
            'access_token' => $request->facebook_token,
        ]
    );

    app()->instance('request', $proxy);

    return Route::dispatch($proxy);
```

**Comment by adaojunior** [comment]
A third option would be:

```

    $proxy = Request::create(
        '/oauth/token',
        'POST',
        [
            'grant_type' => 'social',
            'client_id' => 'YYYYYYYYYYYY',
            'client_secret' => 'XXXXXXXXXXXXXXXXXXXXX',
            'network' => 'facebook',
            'access_token' => $request->facebook_token,
        ]
    );

    return app()->handle($proxy);
```

**Comment by thanush** [comment]
@adaojunior  by using 2nd and 3rd option i'm getting below popup.
![image](https://user-images.githubusercontent.com/6806782/33124565-786eb336-cfa3-11e7-9d3b-c42ebee8365b.png)


is there any reason for that?

**Comment by adaojunior** [comment]
@thanush  I've never seen this popup before. Are you using basic authentication ?
Does it work by doing a call with GuzzleHttp ?

**Comment by josteph** [comment]
This may be caused by wrong callback in `oauth/client` database.

**Comment by ejlocop** [comment]
any updates on this one? 
i got this error too.

@adaojunior what is the difference between those 3 methods? and what is proxy? 

thanks

**Comment by adaojunior** [comment]
>  What is the difference between those 3 methods?

With guzzle you're making a new request to `'/oauth/token'`, with the other options (if I understand this correctly) you're telling Laravel to handle a request using some new params.
Overall they all should work, I find the option 2 and 3 to be easier to debug.

> any updates on this one?

I noticed that I only get the prompt if the `client_id` or `client_secret` is incorrect, so make sure to get the client information from the `oauth_clients` table, `Laravel Password Grant Client` should work fine.

I find that many people get confused on how to use this package so I'll example implementation tomorrow.

**Comment by pierrocknroll** [comment]
Hi @adaojunior 
Indeed, your package seems to be very nice but I don't understand how to implement it.
When I receive a token from facebook, if I call /oauth/token with grant_type : social, it seems that you re-call facebook to get the user, I think I misunderstood something. 
In fact, I'm wondering what code you put in your example in the method protected function authWithFacebook($accessToken).

My flow is, with socialite : 
1. Redirect to facebook to get the code
2. Then call Socialite::driver('facebook')->user() to get the facebook profile then check if I have a user in my database or create it.
3. Returns the access & refresh tokens with passport.

I thought your package will help me to do the third part but maybe I'm totally wrong ? :)

**Comment by kslimani** [comment]
From my understanding, Passport allow you to get a bearer token, for example, using "password" grant method : ie: user send email + password, and your api returns a bearer token (with refresh token) if credentials are correct.

This package allow you to implement another type of grant method : the "social" one. (to retrieve a user bearer token, like the password one and can be used the same way).

All you have to do, is create the social user resolver class which implements the resolve method (from interface) and register it in your application service provider (described in readme file).

It expects a "network" parameter in the payload which is likely a unique social service identifier (facebook, github, etc...) and the access token retrieved from the social network.

If using Socialite to get network provider access token, you are nearly 100% sure this access token data contains an "id" field, which is the user unique identifier from network provider, which can be used as relation to your internal user id. (to retrieve, ie: login - or create ie: register).

Also, ensure you serialize the provider access token in the payload (for example in json) as it is retrieved as a string in the social user provider resolve method.

**Comment by adaojunior** [comment]
I just created an example of how to exchange a access token to a passport token, see: https://github.com/adaojunior/passport-social-grant-example
This is just one way of implementing it, you may be getting the access token on the front-end or maybe mobile, in this case you don't need AuthController::redirect, instead just send your token to AuthController::callback.

**Comment by pierrocknroll** [comment]
Thanks a lot !
So with your solution two request are made to the provider (+ an internal request)

**Comment by GunarajKhatri** [comment]
> But if you prefer to use the "proxy", you will have to do something like this:
> 
> ```
>     $proxy = Request::create(
>         '/oauth/token',
>         'POST',
>         [
>             'grant_type' => 'social',
>             'client_id' => 'YYYYYYYYYYYY',
>             'client_secret' => 'XXXXXXXXXXXXXXXXXXXXX',
>             'network' => 'facebook',
>             'access_token' => $request->facebook_token,
>         ]
>     );
> 
>     app()->instance('request', $proxy);
> 
>     return Route::dispatch($proxy);
> ```

thanks this works for me
