### ISSUE TITLE
Implementation Help

### ISSUE THREAD

**Issue by josteph** [adaojunior/passport-social-grant#24]
I need some help about the implementation (never used socialite with passport before), and found that this package seems to be the answer for me.

So the routes I have:

```
Route::get('login/{provider}', 'SocialLoginController@redirect')->where(['provider' => 'facebook|google']);

Route::get('login/{provider}/callback', 'SocialLoginController@handleRedirectCallback')->where(['provider' => 'facebook|google']);
```

And my current SocialLoginController.php:
```
public function redirect($provider)
    {
        return Socialite::driver($provider)->stateless()->redirect();
    }
public function handleRedirectCallback($provider)
    {
        $socialUserInfo = Socialite::driver($provider)->stateless()->user();
        // etc..
    }
```
So the code above is the very basic authentication for socialite (without passport), and since I want to combine the API to be able to get the access token and refresh token, I need to use passport.

So what I have done until now:
1. Registering the code below in AppServiceProvider
```
$this->app->singleton(SocialUserResolverInterface::class, SocialUserResolver::class);
```
2. Creating `class SocialUserResolver implements SocialUserResolverInterface`
```
public function resolve($network, $accessToken, $accessTokenSecret = null)
    {
        switch ($network) {
            case 'facebook':
                return $this->authWithFacebook($accessToken);
                break;
            case 'google':
                return $this->authWithGoogle($accessToken);
                break;
            default:
                throw SocialGrantException::invalidNetwork();
                break;
        }
    }

   protected function authWithFacebook($accessToken)
    {
        $account = Socialite::driver('facebook')->userFromToken($accessToken);
    }

    protected function authWithGoogle($accessToken)
    {
        $account = Socialite::driver('google')->userFromToken($accessToken);
    }
```

So the questions:
1. When and where should I call the methods inside that class?
2. Do I need to do `use SocialUserResolver` inside SocialLoginController?
3. If my understanding is correct:
- The callback from the socialite should be set to `function resolve` from SocialUserResolver class,
- Then we post grant_type social to oauth/token to get both access_token and refresh_token.

Please help me to clarify things up..
Any suggestion gladly appreciated. Thank you!

**Comment by adaojunior** [comment]
The way this package works is by taking a google|facebook|github **access token** and resolving it into a passport access_token, refresh_token.

You can try it by doing something like this:

```
public function handleRedirectCallback($provider)
{
    $user = Socialite::driver($provider)->stateless()->user();

    $proxy = \Illuminate\Http\Request::create(
        '/oauth/token',
        'POST',
        [
            'grant_type' => 'social',
            'client_id' => 'client-id',
            'client_secret' => 'client-secret',
            'network' => $provider,
            'access_token' => $user->token,
        ]
    );

    return app()->handle($proxy);
}
```

As you can see your now making a call to ` '/oauth/token'`,  and `SocialUserResolver->resolve` will be called.
I'm not quite sure if this package is the right choice for your use case, because you sort of resolving the user twice, the first time you do the redirect and get the user + access token, and then your using the access token to call passport and resolve that access token again.
I'll take some time to think of a better way for you to implement this feature.
Most of my own use cases are with mobile clients, I haven't done anything like your implementation yet.

**Comment by josteph** [comment]
@adaojunior So how does this package work especially in mobile clients ?

Actually I'm going to use this for a mobile application.
So what I get from your explanation is:

1.  Get the access token from github / facebook / google
2. Pass it to the $proxy request above.
3. The `SocialUserResolver->resolve` will be called.
4. It will return back the token_type, access_token, and refresh_token to the client side in json format.
5. The user is authenticated and now able to make request to the API with the Bearer access_token as request header.

If this is correct, I will try to implement in right away. Thank you very much for your time.

**Comment by adaojunior** [comment]
@josteph you're exactly right, usually the mobile gets the facebook|github|google token so you don't need to implement that part on your backend, you just need to receive their `access_token` proxy it with something as simple as:

```
    $proxy = \Illuminate\Http\Request::create(
        '/oauth/token',
        'POST',
        [
            'grant_type' => 'social',
            'client_id' => 'client-id',
            'client_secret' => 'client-secret',
            'network' => 'facebook',
            'access_token' => request('access_token'),
        ]
    );

    return app()->handle($proxy);
```

**Comment by josteph** [comment]
Alright, I managed to solve it. Thank you very much! Nice package btw.
