### ISSUE TITLE
Returning User Details with Grant Token.

### ISSUE THREAD

**Issue by Alien-nick** [adaojunior/passport-social-grant#28]
I successfully set up passport-social-grant package in my project, and it works well, but i am trying to return the user details such as (first name, last name, email) but i am not getting these details to return.

**Comment by adaojunior** [comment]
You need to make an extra request to get that information, `/oauth/token` only returns `access_token `, `refresh_token` and `expires_in`. Passport helps will with authentication, and once your authenticated you can call eg: `api/profile` to get the details that you want about the user. How will you implement that route is entirely up to you.

**Comment by Alien-nick** [comment]
Ok thank you.
