### ISSUE TITLE
[Question] SocialUserResolverInterface arguments

### ISSUE THREAD

**Issue by kslimani** [adaojunior/passport-social-grant#31]
Hi,

@adaojunior what do you think about pass the request object as additional argument in the resolve() method ? 

_(hintypeless to make it backward compatible, expecting ServerRequestInterface instance)_

I think it may make it more powerfull and more customizable. For example, allowing to check more expected form parameters, or headers.

**Comment by kslimani** [comment]
I think this change may also satisfy the use case proposed by #29 (but even more powerfull)

EDIT: i have read also [your comment](https://github.com/adaojunior/passport-social-grant/pull/29#issuecomment-385111733) - i will try this workaround. But i still think it would be "more elegant" to provide request instance in resolve method.

**Comment by adaojunior** [comment]
Hi @kslimani, I'm open to make this addition, I started working on a [brand new version](https://github.com/adaojunior/passport-social-grant/tree/passport-social-grant-v4) of this library, I believe it could be added to that version. Do you mind doing a quick review on this new version and give me some feedback?

**Comment by adaojunior** [comment]
See also [passport-social-grant-example](https://github.com/adaojunior/passport-social-grant-example/blob/passport-social-grant-example-v4/app/Http/Controllers/AuthController.php)

- [config/social-grant.php](https://github.com/adaojunior/passport-social-grant-example/blob/passport-social-grant-example-v4/config/social-grant.php)
- [app/Auth/SocialGrantCodeResolver.php](https://github.com/adaojunior/passport-social-grant-example/blob/passport-social-grant-example-v4/app/Auth/SocialGrantCodeResolver.php)
- [app/Http/Controllers/AuthController.php](https://github.com/adaojunior/passport-social-grant-example/blob/passport-social-grant-example-v4/app/Http/Controllers/AuthController.php)

**Comment by kslimani** [comment]
I did not take a deep look at new changes, but the first thing which comes in my mind is the configuration structure.

I think there should be a single key where value is a key-value array. In this key-value array, the key is a string which is the type of grant, and the value, the class to handle the type of grant.

This may allow the developper to add or remove any type of grant it needs.

For example :

```php
<?php
return [
    'find_a_name' => [
        'social' => App\Auth\SocialGrantAccessTokenResolver::class,
        // [...]
    ],
];
```

Also, maybe one key could be for "handlers" and one key for "resolvers".

**Comment by kslimani** [comment]
And for the resolve method (interface) i think it could be more something like :

```php
public function resolve(ServerRequestInterface $request, array $context);
```

Where `$context` array contents depends on the type of grant. (created by the grant type "handler" class) and where the grant type "resolver" class implements this interface method.

Note: with these changes, the library becomes more than an only "social" grant , it becomes an "any" grant.

**Comment by kslimani** [comment]
My idea is the OAuth request becomes :

```php
$response = $http->post('http://your-app.com/oauth/token', [
    'form_params' => [
        'grant_type' => 'social',
        // Any key-value expected by the configured "social" grant handler class
    ],
]);
```

What about create a new library, for example called "laravel-grant" (will simplify and allow any breaking change from "laravel-social-grant" library) ?
