### ISSUE TITLE
Not support with Laravel 6.x

### ISSUE THREAD

**Issue by HELMAB** [adaojunior/passport-social-grant#42]
<pre>Using version <font color="#4E9A06">^4.0</font> for <font color="#4E9A06">adaojunior/passport-social-grant</font>
<font color="#4E9A06">./composer.json has been updated</font>
<font color="#4E9A06">Loading composer repositories with package information</font>
<font color="#4E9A06">Updating dependencies (including require-dev)</font>
<span style="background-color:#CC0000"><font color="#D3D7CF">Your requirements could not be resolved to an installable set of packages.</font></span>

  Problem 1
    - Installation request for laravel/passport (locked at v7.5.1, required as ^7.2) -&gt; satisfiable by laravel/passport[v7.5.1].
    - adaojunior/passport-social-grant v4.0 requires laravel/passport ^8.0 -&gt; satisfiable by laravel/passport[8.x-dev].
    - adaojunior/passport-social-grant v4.0-beta.1 requires laravel/passport ^8.0 -&gt; satisfiable by laravel/passport[8.x-dev].
    - Conclusion: don&apos;t install laravel/passport 8.x-dev
    - Installation request for adaojunior/passport-social-grant ^4.0 -&gt; satisfiable by adaojunior/passport-social-grant[v4.0, v4.0-beta.1].

<span style="background-color:#CC0000"><font color="#D3D7CF">Installation failed, reverting ./composer.json to its original content.</font></span></pre>

**Comment by adaojunior** [comment]
Hi @HELMAB , have you tried updating laravel/passport as well? The latest version of this package requires Laravel Passport 8. I'll test it on earlier versions and find out if I can support them. I'll keep you updated.
