### ISSUE TITLE
Override "provider" string to support either "provider" or "network"

### ISSUE THREAD

**Issue by sylouuu** [adaojunior/passport-social-grant#43]
Hi @adaojunior 

I've updated my code with the latest version.

I saw that you have changed the parameter "network" by "provider". It's OK but an app for TV that I can't update at all, is using the old version "network". So I can't do the update, the biggest problem is my update is concerning the Laravel 6 upgrade, so with Passport 8 and your latest version too.

Do you have an idea how I can override your logic in my project API to allow both "provider" and "network" values because I can't break the TV app, please?

Idea: allow to customize the parameter name instead of an hard-coded string

Bests

**Comment by adaojunior** [comment]
Hi @sylouuu. I'm looking into this. I like your idea of customizing the parameter name, or I may use a flag to revert to the old name. You can also use the version 3.5 since it is compatible with Laravel 6 and Passport 8. Let me know if you decide to use 3.5, then I won't make your suggested changes to the 4.x version of this package.

**Comment by sylouuu** [comment]
I also like the idea. I would like to use your latest version instead of downgrading.

How do you think you are going to do it? A config file to publish?
How long do you estimate the release? because If you say weeks or months I won't wait that long :)

Bests

**Comment by adaojunior** [comment]
I may use a flag on the `SocialGrant` class, eg:

```
SocialGrant::useNetworkInsteadOfProvider()
```

I believe this is a rare problem and there's no need to make every single param customizable.

**Comment by sylouuu** [comment]
I'm OK with your proposal. When could you release it? :)

Bests

**Comment by adaojunior** [comment]
I'll work on it later today and I'll release it today as well. It is a small change but I'm also overwhelmed with professional projects.

**Comment by adaojunior** [comment]
@sylouuu done. The version 4.0.1 now supports using network instead of provider. I'll keep it undocumented for now since I believe it may cause confusion.

You can continue using the param network with this:

```
SocialGrant:: useNetworkInsteadOfProvider();
```

Let me know if it works for you.

**Comment by sylouuu** [comment]
It works like a charm!

Thx
