### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by neoighodaro** [adaojunior/passport-social-grant#5]
The scope is usually empty when using your package, even when yo uadd the scope. Is there anyway to make it non empty?

**Comment by adaojunior** [comment]
@neoighodaro Adding scope is working fine for me.
Make sure you have middleware `'auth:api'` before checking if scope exists, and that you have registered your scopes.

eg':
```
Passport::tokensCan([
    'place-orders' => 'Place orders',
    'check-status' => 'Check order status',
]);
```

**Comment by neoighodaro** [comment]
I have not created any scopes. I want to use a wildcard scope `*`. It does not work with that. But if you were to try a password grant without creating scopes it would work with a wildcard scope

**Comment by adaojunior** [comment]
Oh I see it now, seems like passport only allow `password` and `personal_access` tokens grant to get "*" scope
[ScopeRepository.php](https://github.com/laravel/passport/blob/1.0/src/Bridge/ScopeRepository.php#L28)

**Comment by pierrocknroll** [comment]
Hello, sorry to reopen an old topic, but how do I pass a '*' scope for a social grant type ? Thanks
