### ISSUE TITLE
oauth1 (Twitter) compatibility

### ISSUE THREAD

**Issue by aliasdoc** [adaojunior/passport-social-grant#6]
Hi, good work @adaojunior but I think it's good to add oauth1 compatibility with using access_token_secret, I made this by modifying these two files:

```php
SocialGrant.php

protected function validateUser(ServerRequestInterface $request)
    {
        $user = $this->resolver->resolve(
            $this->getParameter('network', $request),
            $this->getParameter('access_token', $request),
            $this->getParameter('access_token_secret', $request) <-- add this line
        );


SocialUserResolverInterface.php

public function resolve($network, $accessToken, $accessTokenSecret); <-- add accessTokenSecret param

```

**Comment by adaojunior** [comment]
@aliasdoc thank you, I'll look into it later.

**Comment by adaojunior** [comment]
@aliasdoc I'm not gonna add this to the library, but since you're the one that resolves the user you just need to send the extra field in the request and get it back with `request()->get('access_token_secret')` on `resolve(...)`.
What do you think ?

**Comment by aliasdoc** [comment]
@adaojunior yes, it's a possibility but it breaks concept I think.

**Comment by adaojunior** [comment]
Yes 😞 but also Oauth 1 has been deprecated for a while right ?

**Comment by aliasdoc** [comment]
Not definitely, Twitter for example still uses oauth1 ;)

**Comment by adaojunior** [comment]
This is being addressed in the last update, see https://github.com/adaojunior/passport-social-grant/pull/10 and https://github.com/adaojunior/passport-social-grant/releases/tag/v2.0-beta.1
