### ISSUE TITLE
Passport 2 support

### ISSUE THREAD

**Issue by christiandulson** [adaojunior/passport-social-grant#9]
Hey adaojunior, I'm trying to install the package through Composer and getting this error:

`satisfiable by laravel/passport[1.0.x-dev, v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.
12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.17, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9] but these conflict with your requirements or minimum-s
tability.
`

Your package requires laravel/passport: ^1.0, is it possible to use it somehow with passports actual version?

**Comment by adaojunior** [comment]
Hi @christiandulson, I'll test it with passport 2 soon. Thank you!

**Comment by nLamprok** [comment]
@adaojunior do you have any news on that?

**Comment by adaojunior** [comment]
Hi @christiandulson and @nLamprok 

I started working on it here https://github.com/adaojunior/passport-social-grant/pull/10
I also released a new version https://github.com/adaojunior/passport-social-grant/releases/tag/v2.0-beta.0
It is not tested yet, I'll upgrade my projects and I may add changes to that PR.

**Comment by mayankTUM** [comment]
Hi @adaojunior, I am using Passport 1.0, but while installing your package through composer, I get the following error.

>  [InvalidArgumentException]                                                                                                                                        
>   Could not find package adaojunior/passport-social-grant at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Can you help me with this issue?

Thanks in advance.

**Comment by mayankTUM** [comment]
Resolved it, nevermind.

**Comment by adaojunior** [comment]
Hi, I released a stable version, now you should not get that error even if you remove the minimum-stability.

**Comment by mayankTUM** [comment]
So you do not support Passport 1.0 anymore or what?

**Comment by adaojunior** [comment]
I do, it is a small package so there's not much to do here. What I meant is that previously the package was tagged as beta, but now I released a stable version for both passport 1 and 2.
The 1.x supports passport 1 and the 2.x supports passport 2.

**Comment by mayankTUM** [comment]
Ok. Perfect. Got it.

**Comment by mayankTUM** [comment]
Hi, sorry to bug you again. I am now using version v1.0. But whenever my code reaches this point 

```
$data = [
           'access_token' => $accessToken,
            'network' => 'facebook'
            'client_id'     => env('PASSWORD_CLIENT_ID'),
            'client_secret' => env('PASSWORD_CLIENT_SECRET'),
            'grant_type'    => 'social'
        ];
 $client = new Client();
 $response = $client->post(env('APP_URL') . '/oauth/token', ['form_params' => $data]); 
```

I get the following error in the last line

> Target [Adaojunior\Passport\SocialUserResolverInterface] is not instantiable while building [Laravel\Passport\Http\Controllers\AccessTokenController]

Can you help me with this please?
Thanks

**Comment by adaojunior** [comment]
Is this happening after you starting using 1.0 ?

**Comment by adaojunior** [comment]
btw, did you setup the DI ?

Your `AppServiceProvider.php` should have something like this:

```
$this->app->singleton(SocialUserResolverInterface::class, SocialUserResolver::class);
```

**Comment by mayankTUM** [comment]
Yes, this happened after I started using v1.0. And, I have the DI already setup.

**Comment by adaojunior** [comment]
Ok, please create a ticket for it and I'll look into it later, but it makes not sense since 1.0 is exactly the same as the beta version we used to have.

**Comment by cvictorjose** [comment]
Hi Adao..
i have this problem 
[Symfony\Component\Debug\Exception\FatalThrowableError]                       
  Cannot instantiate interface Adaojunior\Passport\SocialUserResolverInterface 
I dont understand why!! please can you send me more info
thanks
